version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      timezone: 'Europe/Berlin'
    labels:
      - 'dependabot'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      timezone: 'Europe/Berlin'
    labels:
      - 'dependabot'
