packages:
  - '.'

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - '@payloadcms/db-sqlite@3.90.0'
  - '@payloadcms/drizzle@3.90.0'
  - '@payloadcms/email-nodemailer@3.90.0'
  - '@payloadcms/email-resend@3.90.0'
  - '@payloadcms/graphql@3.90.0'
  - '@payloadcms/live-preview-react@3.90.0'
  - '@payloadcms/live-preview@3.90.0'
  - '@payloadcms/next@3.90.0'
  - '@payloadcms/payload-cloud@3.90.0'
  - '@payloadcms/plugin-cloud-storage@3.90.0'
  - '@payloadcms/plugin-mcp@3.90.0'
  - '@payloadcms/plugin-search@3.90.0'
  - '@payloadcms/richtext-lexical@3.90.0'
  - '@payloadcms/storage-s3@3.90.0'
  - '@payloadcms/storage-vercel-blob@3.90.0'
  - '@payloadcms/translations@3.90.0'
  - '@payloadcms/ui@3.90.0'
  - payload@3.90.0

overrides:
  dompurify: ^3.4.13
  esbuild: ^0.28.1
  js-cookie: ^3.0.7
