packages:
  - '.'

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - '@payloadcms/db-sqlite@3.90.2'
  - '@payloadcms/drizzle@3.90.2'
  - '@payloadcms/email-nodemailer@3.90.2'
  - '@payloadcms/email-resend@3.90.2'
  - '@payloadcms/graphql@3.90.2'
  - '@payloadcms/live-preview-react@3.90.2'
  - '@payloadcms/live-preview@3.90.2'
  - '@payloadcms/next@3.90.2'
  - '@payloadcms/payload-cloud@3.90.2'
  - '@payloadcms/plugin-cloud-storage@3.90.2'
  - '@payloadcms/plugin-mcp@3.90.2'
  - '@payloadcms/plugin-search@3.90.2'
  - '@payloadcms/richtext-lexical@3.90.2'
  - '@payloadcms/storage-s3@3.90.2'
  - '@payloadcms/storage-vercel-blob@3.90.2'
  - '@payloadcms/translations@3.90.2'
  - '@payloadcms/ui@3.90.2'
  - payload@3.90.2

overrides:
  dompurify: ^3.4.13
  esbuild: ^0.28.1
  js-cookie: ^3.0.7
  ip-address: ^10.5.1
  nodemailer: ^10.0.2
  undici@6: ^6.28.1
  undici@7: ^7.29.1
  fast-uri: ^3.1.7
