/**
 * WordPress to Payload CMS Posts Migration Script (SKELETON)
 *
 * TODO: This script needs full implementation. When implementing, follow the pattern from migrateArtists.ts
 *
 * Prerequisites:
 * 1. Export posts from both WordPress instances (EN and DE)
 * 2. Place files in scripts/wordpress/data/all-en.xml and all-de.xml
 * 3. Run utils/uploadLocalMedia.ts first to upload all media files
 *
 * Media Handling (Vercel Blob):
 * - Load images-id-map.json (generated by uploadLocalMedia.ts)
 * - Posts use 'images' collection for featured images
 * - Use findMediaByFilename(filename, 'images', dryRun) pattern
 * - Update image metadata: collection: 'images', field: 'alt'
 *
 * Reference Implementation:
 * @see scripts/wordpress/migrateArtists.ts - Full migration pattern with media handling
 * @see scripts/wordpress/utils/uploadLocalMedia.ts - Generates images-id-map.json
 *
 * Collection Schema:
 * - Posts.image -> relationTo: 'images' (already updated for Vercel Blob)
 *
 * https://payloadcms.com/posts/blog/how-to-migrate-from-wordpress-to-payload
 */

import { XMLParser } from 'fast-xml-parser'
import * as fs from 'fs/promises'
import { getPayload } from 'payload'

export const migratePosts = async () => {
  console.log('Starting migration:')

  const awaitConfig = await import('../../src/payload.config')
  const config = awaitConfig.default
  const payload = await getPayload({ config })

  // TODO: Load images-id-map.json
  // const imagesIdMap = JSON.parse(await fs.readFile('./scripts/wordpress/data/images-id-map.json', 'utf-8'))

  // Assemble the posts data
  const xmlData = await fs.readFile('./scripts/wordpress/data/posts.xml', 'utf8')

  const parser = new XMLParser()
  const wpData = parser.parse(xmlData)

  for (const blogPost of wpData.rss.channel.item) {
    console.log({ blogPost })
    // TODO: Implement post migration logic
    // - Parse post meta (featured image via _thumbnail_id)
    // - Convert HTML to Lexical format
    // - Map featured image using findMediaByFilename(filename, 'images', dryRun)
    // - Create/update post with localized content
    // - Update image alt text in 'images' collection
  }
}

migratePosts()
